/*
 * Autonomous.h
 *
 *  Created on: Jan 28, 2016
 *      Author: Siddhesh
 */

#ifndef AUTONOMOUS_H_
#define AUTONOMOUS_H_


namespace Autonomous
{
	enum Defense
	{
		LOW_BAR = 0,
		PORTCULLIS = 1,
		CHEVAL_DE_FRISES = 2,
		MOAT = 3,
		RAMPARTS = 4,
		DRAWBRIDGE = 5,
		SALLY_PORT = 6,
		ROCK_WALL = 7,
		ROUGH_TERRAIN = 8
	};
	enum Goals
	{
		HIGH,
		LOW,
		NONE
	};
	enum AllAutoPlays
	{
		//new new list
		//named in a pattern of 1st Dial (shooting), 2nd Dial (Starting Position (SP)), 3rd Dial (defense)
		//DoNothing play
		NOSHOOTING_SP0_DEFNONE = 0,
		//MoveToDefense plays
		NOSHOOTING_SP1_DEFNONE = 8,		//SP = low bar
		NOSHOOTING_SP2_DEFNONE = 16,	//SP = A
		NOSHOOTING_SP3_DEFNONE = 24,	//SP = B
		NOSHOOTING_SP4_DEFNONE = 32,	//SP = C
		NOSHOOTING_SP5_DEFNONE = 40,	//SP = D
		//CrossDefense
		NOSHOOTING_SP1_DEFPORTCULLIS = 72,
		NOSHOOTING_SP1_DEFCHEVALDEFRISES = 136,
		NOSHOOTING_SP1_DEFMOAT = 200,
		NOSHOOTING_SP1_DEFRAMPARTS = 264,
		NOSHOOTING_SP1_DEFDRAWBRIDGE = 328,
		NOSHOOTING_SP1_DEFSALLYPORT = 392,
		NOSHOOTING_SP1_DEFROUGHTERRAIN = 456,		//ROUGHTERRAIN = rock wall/rough terrain/low bar

		NOSHOOTING_SP2_DEFPORTCULLIS = 80,
		NOSHOOTING_SP2_DEFCHEVALDEFRISES = 144,
		NOSHOOTING_SP2_DEFMOAT = 208,
		NOSHOOTING_SP2_DEFRAMPARTS = 272,
		NOSHOOTING_SP2_DEFDRAWBRIDGE = 336,
		NOSHOOTING_SP2_DEFSALLYPORT = 400,
		NOSHOOTING_SP2_DEFROUGHTERRAIN = 464,

		NOSHOOTING_SP3_DEFPORTCULLIS = 88,
		NOSHOOTING_SP3_DEFCHEVALDEFRISES = 152,
		NOSHOOTING_SP3_DEFMOAT = 216,
		NOSHOOTING_SP3_DEFRAMPARTS = 280,
		NOSHOOTING_SP3_DEFDRAWBRIDGE = 344,
		NOSHOOTING_SP3_DEFSALLYPORT = 408,
		NOSHOOTING_SP3_DEFROUGHTERRAIN = 472,

		NOSHOOTING_SP4_DEFPORTCULLIS = 96,
		NOSHOOTING_SP4_DEFCHEVALDEFRISES = 160,
		NOSHOOTING_SP4_DEFMOAT = 224,
		NOSHOOTING_SP4_DEFRAMPARTS = 288,
		NOSHOOTING_SP4_DEFDRAWBRIDGE = 352,
		NOSHOOTING_SP4_DEFSALLYPORT = 416,
		NOSHOOTING_SP4_DEFROUGHTERRAIN = 480,

		NOSHOOTING_SP5_DEFPORTCULLIS = 104,
		NOSHOOTING_SP5_DEFCHEVALDEFRISES = 168,
		NOSHOOTING_SP5_DEFMOAT = 232,
		NOSHOOTING_SP5_DEFRAMPARTS = 296,
		NOSHOOTING_SP5_DEFDRAWBRIDGE = 360,
		NOSHOOTING_SP5_DEFSALLYPORT = 424,
		NOSHOOTING_SP5_DEFROUGHTERRAIN = 488,
		//CrossDefenceAndShoot
		SHOOTINGLOW_SP1_DEFPORTCULLIS = 73,
		SHOOTINGLOW_SP1_DEFCHEVALDEFRISES = 137,
		SHOOTINGLOW_SP1_DEFMOAT = 201,
		SHOOTINGLOW_SP1_DEFRAMPARTS = 265,
		SHOOTINGLOW_SP1_DEFDRAWBRIDGE = 329,
		SHOOTINGLOW_SP1_DEFSALLYPORT = 393,
		SHOOTINGLOW_SP1_DEFROUGHTERRAIN = 457,

		SHOOTINGLOW_SP2_DEFPORTCULLIS = 81,
		SHOOTINGLOW_SP2_DEFCHEVALDEFRISES = 145,
		SHOOTINGLOW_SP2_DEFMOAT = 209,
		SHOOTINGLOW_SP2_DEFRAMPARTS = 273,
		SHOOTINGLOW_SP2_DEFDRAWBRIDGE = 337,
		SHOOTINGLOW_SP2_DEFSALLYPORT = 401,
		SHOOTINGLOW_SP2_DEFROUGHTERRAIN = 465,

		SHOOTINGLOW_SP3_DEFPORTCULLIS = 89,
		SHOOTINGLOW_SP3_DEFCHEVALDEFRISES = 153,
		SHOOTINGLOW_SP3_DEFMOAT = 217,
		SHOOTINGLOW_SP3_DEFRAMPARTS = 281,
		SHOOTINGLOW_SP3_DEFDRAWBRIDGE = 345,
		SHOOTINGLOW_SP3_DEFSALLYPORT = 409,
		SHOOTINGLOW_SP3_DEFROUGHTERRAIN = 473,

		SHOOTINGLOW_SP4_DEFPORTCULLIS = 97,
		SHOOTINGLOW_SP4_DEFCHEVALDEFRISES = 161,
		SHOOTINGLOW_SP4_DEFMOAT = 225,
		SHOOTINGLOW_SP4_DEFRAMPARTS = 289,
		SHOOTINGLOW_SP4_DEFDRAWBRIDGE = 353,
		SHOOTINGLOW_SP4_DEFSALLYPORT = 417,
		SHOOTINGLOW_SP4_DEFROUGHTERRAIN = 481,

		SHOOTINGLOW_SP5_DEFPORTCULLIS = 105,
		SHOOTINGLOW_SP5_DEFCHEVALDEFRISES = 169,
		SHOOTINGLOW_SP5_DEFMOAT = 233,
		SHOOTINGLOW_SP5_DEFRAMPARTS = 297,
		SHOOTINGLOW_SP5_DEFDRAWBRIDGE = 361,
		SHOOTINGLOW_SP5_DEFSALLYPORT = 425,
		SHOOTINGLOW_SP5_DEFROUGHTERRAIN = 489,

		SHOOTINGHIGH_SP1_DEFPORTCULLIS = 74,
		SHOOTINGHIGH_SP1_DEFCHEVALDEFRISES = 138,
		SHOOTINGHIGH_SP1_DEFMOAT = 202,
		SHOOTINGHIGH_SP1_DEFRAMPARTS = 266,
		SHOOTINGHIGH_SP1_DEFDRAWBRIDGE = 330,
		SHOOTINGHIGH_SP1_DEFSALLYPORT = 394,
		SHOOTINGHIGH_SP1_DEFROUGHTERRAIN = 458,

		SHOOTINGHIGH_SP2_DEFPORTCULLIS = 82,
		SHOOTINGHIGH_SP2_DEFCHEVALDEFRISES = 146,
		SHOOTINGHIGH_SP2_DEFMOAT = 210,
		SHOOTINGHIGH_SP2_DEFRAMPARTS = 274,
		SHOOTINGHIGH_SP2_DEFDRAWBRIDGE = 338,
		SHOOTINGHIGH_SP2_DEFSALLYPORT = 402,
		SHOOTINGHIGH_SP2_DEFROUGHTERRAIN = 466,

		SHOOTINGHIGH_SP3_DEFPORTCULLIS = 90,
		SHOOTINGHIGH_SP3_DEFCHEVALDEFRISES = 154,
		SHOOTINGHIGH_SP3_DEFMOAT = 218,
		SHOOTINGHIGH_SP3_DEFRAMPARTS = 282,
		SHOOTINGHIGH_SP3_DEFDRAWBRIDGE = 346,
		SHOOTINGHIGH_SP3_DEFSALLYPORT = 410,
		SHOOTINGHIGH_SP3_DEFROUGHTERRAIN = 474,

		SHOOTINGHIGH_SP4_DEFPORTCULLIS = 98,
		SHOOTINGHIGH_SP4_DEFCHEVALDEFRISES = 162,
		SHOOTINGHIGH_SP4_DEFMOAT = 226,
		SHOOTINGHIGH_SP4_DEFRAMPARTS = 290,
		SHOOTINGHIGH_SP4_DEFDRAWBRIDGE = 354,
		SHOOTINGHIGH_SP4_DEFSALLYPORT = 418,
		SHOOTINGHIGH_SP4_DEFROUGHTERRAIN = 482,

		SHOOTINGHIGH_SP5_DEFPORTCULLIS = 106,
		SHOOTINGHIGH_SP5_DEFCHEVALDEFRISES = 170,
		SHOOTINGHIGH_SP5_DEFMOAT = 234,
		SHOOTINGHIGH_SP5_DEFRAMPARTS = 298,
		SHOOTINGHIGH_SP5_DEFDRAWBRIDGE = 362,
		SHOOTINGHIGH_SP5_DEFSALLYPORT = 426,
		SHOOTINGHIGH_SP5_DEFROUGHTERRAIN = 490
	};
}

#endif /* AUTONOMOUS_H_ */
